Traceback (most recent call last):
  File "F:\Desktop\RWE+\LevelProcess.py", line 120, in mainprocessupdate
    self.mainprocess.update()
  File "F:\Desktop\RWE+\LevelProcess.py", line 538, in update
    self.menu.blit()
  File "F:\Desktop\RWE+\TE.py", line 169, in blit
    self.insertpattern_pen(cposxo, cposyo)
  File "F:\Desktop\RWE+\TE.py", line 259, in insertpattern_pen
    self.pattern_placer4(xpos, ypos)
  File "F:\Desktop\RWE+\TE.py", line 320, in pattern_placer4
    self.set(savedcat, savedtool)
  File "F:\Desktop\RWE+\TE.py", line 512, in set
    self.selector.setbyname(name, fromfavs=usefavs, category=cat)
  File "F:\Desktop\RWE+\widgets.py", line 814, in setbyname
    self.currentitem = self.data[self.currentcategory]["items"].index(tile)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: None is not in list
This is why RWE+ crashed^^^
Sorry