Traceback (most recent call last):
  File "F:\Desktop\RWE+\LevelProcess.py", line 120, in mainprocessupdate
    self.mainprocess.update()
  File "F:\Desktop\RWE+\LevelProcess.py", line 529, in update
    self.doevents()
  File "F:\Desktop\RWE+\LevelProcess.py", line 517, in doevents
    self.keypress()
  File "F:\Desktop\RWE+\LevelProcess.py", line 490, in keypress
    self.menu.send(pressed)
  File "F:\Desktop\RWE+\menuclass.py", line 855, in send
    super().send(message)
  File "F:\Desktop\RWE+\menuclass.py", line 593, in send
    getattr(self, message[1:])()
  File "F:\Desktop\RWE+\PE.py", line 442, in cat_prev_propupdate
    self.cat_prev()
  File "F:\Desktop\RWE+\PE.py", line 448, in cat_prev
    self.selector.left()
  File "F:\Desktop\RWE+\widgets.py", line 777, in left
    self.onclick("set")
  File "F:\Desktop\RWE+\widgets.py", line 691, in onclick
    self.callback(self.selecteditem)
                  ^^^^^^^^^^^^^^^^^
  File "F:\Desktop\RWE+\widgets.py", line 845, in selecteditem
    return self.data[self.currentcategory]["items"][self.currentitem]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
This is why RWE+ crashed^^^
Sorry