Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\RWE+\LevelProcess.py", line 120, in mainprocessupdate
    self.mainprocess.update()
  File "C:\Users\Admin\Desktop\RWE+\LevelProcess.py", line 538, in update
    self.menu.blit()
  File "C:\Users\Admin\Desktop\RWE+\TE.py", line 186, in blit
    self.destroy(x + rect.x, y + rect.y)
  File "C:\Users\Admin\Desktop\RWE+\menuclass.py", line 1099, in destroy
    clearitem(posx - 1, posy - 1, tile["data"][1] - 1)
  File "C:\Users\Admin\Desktop\RWE+\menuclass.py", line 1047, in clearitem
    backx = mx - int((itm["size"][0] * .5) + .5) + 1
                      ~~~^^^^^^^^
KeyError: 'size'
This is why RWE+ crashed^^^
Sorry